### ISSUE TITLE
Fatal error on launch

### ISSUE THREAD

**Issue by geeklyhallows** [emperorshammer/issues-incoming-queue#13]
[TTT3 Crash.log](https://github.com/emperorshammer/issues-incoming-queue/files/6437619/TTT3.Crash.log)

**Comment by SmTaUcM** [comment]
Python error on TTT3 launch:

Traceback (most recent call last):
  File "TTT3.py", line 337, in __init__
  File "TTT3.py", line 473, in initialGUISetup
  File "TTT3.py", line 2926, in loadRibbons
PermissionError: [Errno 13] Permission denied: 'data\\ribbons_g.inc'

**Comment by SmTaUcM** [comment]
Issue resolved by user moving the 'TTT3' folder off the 'Desktop' to a new location. Suspect Windows/Norton Anti-RansomeWare was preventing TTT3 from writing to the 'ribbons_g.inc' file for protection.

**Comment by SmTaUcM** [comment]
TTT3_readme.htm - Known issues to be updated with:
"In some instances TTT3 may generate a 'Fatal error detected - Failed to execute script TTT3' warning. This has been resolved in some cases by relocating the 'TTT3' installation folder away from the Windows Desktop or Downloads/Pictures directories.
