### ISSUE TITLE
TTT3 - Program crashes when generating Uniform for Cadet

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#76]
I was checking to see if I could make a uniform for a new cadet to show them what our uniforms would look like. Example PIN 56248, after importing the profile and selecting dress uniform, the program crashes back to desktop asking if id like to submit a windows report.

![image](https://user-images.githubusercontent.com/74426625/158652305-05140679-5f7f-484e-8d16-1f704c30bbb6.png)

![image](https://user-images.githubusercontent.com/74426625/158652342-76212b5e-a56d-4910-b7eb-aee9d2574130.png)

Creating a blank uniform without importing a PIN works fine

**Comment by SmTaUcM** [comment]
Bug reproduced on my system also.

TTT3 Crash Log reports:

ERROR:root:

-----Crash Information:-----
ERROR:root:unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "TTT3.py", line 890, in btn_dressMethod
  File "TTT3.py", line 983, in showPreviewDialog
  File "TTT3.py", line 1296, in renderPreview
  File "TTT3.py", line 1897, in createDressPov
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
ERROR:root:

-----System Information:-----
ERROR:root:Windows Version: Windows-10-10.0.19041-SP0 64-bit.
ERROR:root:Processor: Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
ERROR:root:Python Version: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)]
ERROR:root:

-----TTT3 Settings:-----

**Comment by turtlexiv** [comment]
I guess the cadet's level of n00b couldn't be handled by TTT3? :-P

**Comment by SmTaUcM** [comment]
Haha close, it's actually the API data being incorrect

// 20220316185410
// https://api.emperorshammer.org/pilot/56248

{
  "PIN": 56248,
  "label": "CT Grescko Keldan",
  "description": "TRN/CT Grescko Keldan/IWATS",
  "profile": "https://api.emperorshammer.org/record.php?pin=56248&type=profile",
  "email": "Ckelley0111@hotmail.com",
  "rank": "Cadet",
  "rankAbbr": "CT",
  "rankImage": "https://api.emperorshammer.org/images/ranks/original/CT.png",
  "name": "Grescko Keldan",
  "callsign": "None",
  "position": "TRN",
  "IDLine": "TRN/CT Grescko Keldan/IWATS",
  "medalLine": null,
  "IWATSLine": null,
  "FlightWing": {
    "label": "Not Flight Certified",
    "image": null
  },
  "FCHG": {
    "total": 0,
    "label": "Unrated"
  },
  "CR": {
    "total": 0,
    "label": "Unrated"
  },
  "PvE": {
    "total": 0,
    "label": "Unrated"
  },
  "battles": 0,
  "missions": null,
  "sqnSlot": null,
  "TTT": {
    "position": null,
    "pilotWings": 0
  },
  "medals": [
    
  ]
}

Shows his TTT.position as "null" and not "TRN"

**Comment by turtlexiv** [comment]
Oh, so it's my fault? Damn. :-P

**Comment by SmTaUcM** [comment]
The workaround is just to manually make a TRN -> CT profile and hit "Dress Uniform"

But yes, the best fix is to correct the API :P (glad I dodged that one! ;) )

**Comment by turtlexiv** [comment]
Actually, you should handle malformed data better. So there :-P

**Comment by SmTaUcM** [comment]
True, i'll add some error handling at my end to. Work for everyone I say!

**Comment by SmTaUcM** [comment]
Transferring to TTT3 repo for work
